live:
  - name: Ethereum
    networks:
      - chainid: 1
        explorer: https://api.etherscan.io/api
        host: $ETH_RPC_ENDPOINT
        id: ethereum
        name: Ethereum Mainnet (Infura)
  - name: BSC
    networks:
      - chainid: 56
        host: https://bsc-dataseed2.defibit.io/
        id: bsc
        name: bsc
        explorer: https://api.bscscan.com/api
  - name: MATIC
    networks:
      - chainid: 137
        host: $MATIC_RPC_ENDPOINT
        id: matic
        name: matic
  - name: HECO
    networks:
      - chainid: 128
        host: https://http-mainnet.hecochain.com
        id: heco-mainnet
        name: heco-mainnet
development:
  - cmd: ganache-cli
    cmd_settings:
      accounts: 10
      evm_version: istanbul
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: development
    name: Ganache-CLI
